### ISSUE TITLE
Improve dependy trees

### ISSUE THREAD

**Issue by jeremenichelli** [Jam3/slot-machine-button#1]
I think React related packages and GSAP should be peer dependencies and not save dependencies so user is not forced to re-download packages that are already in used on the project.

**Comment by neo** [comment]
They are indeed peer dependencies, thank you!

**Comment by neo** [comment]
@jeremenichelli do you think this could be close since it's answered?

**Comment by jeremenichelli** [comment]
For sure @neo!

**Comment by neo** [comment]
Thanks @jeremenichelli 🎉
